# --- BUILD STAGE ---
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Sadece csproj dosyasını kopyala (doğru path ile)
COPY e-commerce-Backend/commerce.API/*.csproj ./

# NuGet paketlerini indir
RUN dotnet restore

# Tüm backend source'u kopyala
COPY e-commerce-Backend/commerce.API/. ./

# Publish et
RUN dotnet publish -c Release -o /app/publish

# --- RUNTIME STAGE ---
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

# Yayınlanan dosyaları runtime içine kopyala
COPY --from=build /app/publish .

# Kestrel'in 80 portundan dinlemesi için
ENV ASPNETCORE_URLS=http://+:80

EXPOSE 80

# Proje DLL'in doğru: commerce.API.dll
ENTRYPOINT ["dotnet", "commerce.API.dll"]
